name: Deploy to Nekoweb
  # You may pin to the exact commit or the version.
  # uses: mp-pinheiro/nekoweb-deploy@88b0da577834d4f4f717af9a3007a5d0b2d33df4
  uses: mp-pinheiro/nekoweb-deploy@0.2.8
  with:
    # API key for Nekoweb
    API_KEY: a3258159f8c70fd1ecbfe529bdfd3bb588343c4127c519a38e62eb96e8122693
    # Local build directory to deploy
    BUILD_DIR: /eggy.nekoweb.org
    # Remote directory to deploy to
    DEPLOY_DIR: /eggy.nekoweb.org# default is /
    # Your NekoWeb page name (your username unless you use a custom domain).
    NEKOWEB_PAGENAME: eggy.nekoweb.org
    # Also delete remote files that don't exist locally
    CLEANUP: false # optional, default is False
    # Delay between Nekoweb API requests (in seconds)
    DELAY: # optional
    # Number of times to retry the Nekoweb API request
    RETRY_ATTEMTPS: # optional
    # Delay between Nekoweb API request retries (in seconds) when rate limited
    RETRY_DELAY: # optional
    # Exponential backoff for Nekoweb API request retries
    RETRY_EXP_BACKOFF: # optional
    # A secret key used to encrypt the file states. Must be a 32-byte URL-safe base64-encoded string
    ENCRYPTION_KEY: # optional
    # Enable debug mode
    DEBUG: # optional
          
